# API Configurations
api:
  id: "18629858"

healthcheck.api.id: "00000001"

sfcc:
  org:
    clientId: "13cf2aa3-3684-4bd7-a010-be940606edbb"
    shortCode: "h9rwdyix"
    organizationId: "f_ecom_bdkb_dev"
    siteId: "palacio-MX"
    scope: "SALESFORCE_COMMERCE_API:bdkb_dev sfcc.orders sfcc.orders.rw"
  
  token:
    base_path: "/dw/oauth2"
    host: "account.demandware.com"
    path: "/access_token"


  order:
    base_path: "/checkout/orders/v1/organizations/f_ecom_bdkb_dev"
    host: "h9rwdyix.api.commercecloud.salesforce.com"
    path: "/orders"

anypoint-mq:
  connection:
    url: "https://mq-us-west-2.anypoint.mulesoft.com/api/v1/organizations/48335c82-2ddc-455c-aafb-8c7e3a61fb77/environments/a9e0e4df-4e41-45e9-ba3b-7d751756963e"
    clientId: "17714a585d674b0ab6462f878bb64de9"
  queue:
    push: "FIFO.SFCC.PUSH.ORDER.EVENT.SYNC.OUT.DEV"
  config:
    fetchSize: "1"
    frecuency: "1000"
  ack:
    timeOut: "60000" 