#Common App Properties
api:
  id: "59241"
 
env.port: "${https.port}"

app:
  datsi:
    aws:
      s3:
        region: "us-gov-east-1"
        bucket: "pdf-app-s3-js-poc"
        timeout: "10000"
  pnm:
    aws:
      s3:
        region: "us-east-1"
        bucket: "max-pnm-provider-files"
        folder: "/providerfiles/"
        timeout: "10000"
  postgres:
    db:
      host: "max-ves-esr-db-poc.cluster-ro-c7thtp1pqvt7.us-gov-east-1.rds.amazonaws.com"
      port: "5432"
      database: "cenl_db"

error:
  sfcoresapi:
    host: "vems-mule-sfcore-sapi-dev.usg-w1.gov.cloudhub.io"
    port: "443"
  cloudhub:
    environment: "075a1f44-74c5-485f-a9d3-a73d21437302"