#Common App Properties
api:
  id: "59241"
 
env.port: "${https.port}"

app:
  datsi:
    aws:
      s3:
        region: "us-gov-east-1"
        bucket: "pdf-app-s3-js-poc"
        timeout: "10000"

error:
  sfcoresapi:
    host: "vems-mule-sfcore-sapi-dev.usg-w1.gov.cloudhub.io"    
  cloudhub:
    environment: "075a1f44-74c5-485f-a9d3-a73d21437302"