#Common App Properties
api:
  id: "58040"
   
env.port: "${https.private.port}"

app:
  datsi:
    aws:
      s3:
        region: "us-gov-east-1"
        bucket: "pdf-app-s3-js-poc"
        timeout: "10000"

error:
  sfcoresapi:
    host: "replace-it"    
  cloudhub:
    environment: "replace-it"