#%RAML 1.0
title: Maximus VES Practice Match Process API (vems-mule-pm-papi)
description: Process API responsible to integrate Practice Match REST API to recovery providers information
version: v1
mediaType: 
  - application/json
protocols:
  - HTTP
  - HTTPS
types:
  ListDataType: !include DataTypes/ResponsesDataType.raml
  ProviderType: !include DataTypes/ResponseDataType.raml

traits:
  404-trait: !include /exchange_modules/a49d2bd5-98e7-47cb-be7d-a153583e60a6/common-raml-fragments/1.0.0/traits/json/404-trait.raml
  200-trait: !include /exchange_modules/a49d2bd5-98e7-47cb-be7d-a153583e60a6/common-raml-fragments/1.0.0/traits/json/200-trait.raml
  500-trait: !include /exchange_modules/a49d2bd5-98e7-47cb-be7d-a153583e60a6/common-raml-fragments/1.0.0/traits/json/500-trait.raml
  client-id-required: !include ./exchange_modules/a49d2bd5-98e7-47cb-be7d-a153583e60a6/common-raml-fragments/1.0.0/traits/common/client-id-trait.raml

/process:
  /trigger:
    is:
      - client-id-required
    post:
      description: Create endpoint to trigger sync manually
      displayName: trigger sync
      body:
        application/json:
          examples:
            {
              "startdate" : "01/01/2020",
              "enddate" : "01/02/2020"
            }
  /response/{responseId}:
     is: 
      - 200-trait
      - 404-trait
      - 500-trait
      - client-id-required
     get:
      description: Get Provider Information associated to Response ID
  /responses/list:
      is:
        - 500-trait
        - client-id-required
      get:
        description: Get all ResponseID (internal PracticeMatch ID for job application) and AlternateOpportunityID
        queryParameters:
          startDate:
            description: Start Date Practice Match batch execution. YYYY/MM/DD format
            type: string
            required: true
            example: '2023/08/20'
          endDate:
            description: End Date Practice Match batch execution. YYYY/MM/DD format
            type: string
            required: true
            example: '2023/08/23'
        responses:
          200:
            description: Success Response
            body:
              application/json:
                type: ListDataType
                example: !include examples/ResponsesSuccess.raml
              