#%RAML 1.0 NamedExample

{
    "BankAccountNumber": "XXXX9655",
    "CountryCode": "US",
    "BankBranchIdentifier": 300562,
    "BankIdentifier": 298992,
    "BankAccountId": 300100181126859,
    "CurrencyCode": "USD",
    "IBAN": null,
    "CheckDigits": null,
    "AccountType": "SAVINGS",
    "AccountSuffix": null,
    "AgencyLocationCode": null,
    "AllowInternationalPaymentIndicator": "Y",
    "SecondaryAccountReference": null,
    "StartDate": "2019-10-22",
    "EndDate": "4712-12-31",
    "BankAccountName": "Abc Xyz",
    "AlternateAccountName": null,
    "BankBranchPartyIndicator": "Y",
    "BankName": "Citi Bank",
    "BankNumber": null,
    "BankBranchName": "Citi Bank",
    "BankBranchNumber": "64251060",
    "BIC": null,
    "VendorId": null,
    "PersonId": null,
    "Intent": "Supplier",
    "PartyId": 333937,
    "accountOwners": [
        {
            "AccountOwnerPartyIdentifier": 333937,
            "AccountOwnerPartyNumber": "139161",
            "AccountOwnerPartyName": "JACK N JILL INC",
            "PrimaryOwnerIndicator": "Y",
            "StartDate": "2019-10-22",
            "EndDate": "4712-12-31",
            "AccountOwnerId": 300100181126860,
            "Intent": "Supplier",
            "PersonId": null,
            "links": [
                {
                    "rel": "self",
                    "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859/child/accountOwners/300100181126860",
                    "name": "accountOwners",
                    "kind": "item",
                    "properties": {
                        "changeIndicator": "ACED0005737200136A6176612E7574696C2E41727261794C6973747881D21D99C7619D03000149000473697A65787000000001770400000001737200116A6176612E6C616E672E496E746567657212E2A0A4F781873802000149000576616C7565787200106A6176612E6C616E672E4E756D62657286AC951D0B94E08B02000078700000000178"
                    }
                },
                {
                    "rel": "canonical",
                    "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859/child/accountOwners/300100181126860",
                    "name": "accountOwners",
                    "kind": "item"
                },
                {
                    "rel": "parent",
                    "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859",
                    "name": "externalBankAccounts",
                    "kind": "item"
                },
                {
                    "rel": "lov",
                    "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859/child/accountOwners/300100181126860/lov/PartyVVOVA",
                    "name": "PartyVVOVA",
                    "kind": "collection"
                }
            ]
        }
    ],
    "links": [
        {
            "rel": "self",
            "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859",
            "name": "externalBankAccounts",
            "kind": "item",
            "properties": {
                "changeIndicator": "ACED0005737200136A6176612E7574696C2E41727261794C6973747881D21D99C7619D03000149000473697A65787000000001770400000001737200116A6176612E6C616E672E496E746567657212E2A0A4F781873802000149000576616C7565787200106A6176612E6C616E672E4E756D62657286AC951D0B94E08B02000078700000000178"
            }
        },
        {
            "rel": "canonical",
            "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859",
            "name": "externalBankAccounts",
            "kind": "item"
        },
        {
            "rel": "lov",
            "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859/lov/PersonPVA",
            "name": "PersonPVA",
            "kind": "collection"
        },
        {
            "rel": "child",
            "href": "https://servername.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05/externalBankAccounts/300100181126859/child/accountOwners",
            "name": "accountOwners",
            "kind": "collection"
        }
    ]
}