#%RAML 1.0 NamedExample

{
    "Supplier": "INT Supplier with Address Updated",
    "TaxOrganizationType": "Corporation",
    "BusinessRelationship": "Spend Authorized",
    "DUNSNumber": "016082023",
    "TaxpayerCountry": "United States",
    "TaxpayerId": "0016082023",
    "addresses": [
        {
            "SupplierAddressId": 300000002336645,
            "AddressName": "Headquarter",
            "Country": "United States",
            "AddressLine1": "Example Road updated",
            "City": "Redwood City",
            "State": "CA",
            "PostalCode": "94065",
            "AddressPurposeOrderingFlag": true,
            "AddressPurposeRemitToFlag": true,
            "AddressPurposeRFQOrBiddingFlag": false
        }
    ]
}