https:
  keyPass: "![LMwU9lU49ETVhX81ziCo4w==]"

app:
  salesforce:
    cloud:
      auth:
        username: "![JD0h3saayxLmTdB/7BF9QDYatvXQh+NOQA1njUui2EJEoBXc+85IbcyXjEDF5V3P]"
        password: "![k9/vDqF8x10bDUN2qbINeg==]"
        consumerKey: "![y51djiH6fl6bvgWEhY1HX5SrqYCGYh8jGhQq3Q32cMaMFd32d6Jbyb1Itjm+I6HYmmK2WaEkrmf/O4KsyFMrfYcAbld9oBK4itvaaJQ0iDX7iDn4ZdD57Q==]"
        consumerSecret: "![INdcQuS4NRwz4cJr7eWHZiFHwiPyTyx/D9Qimz5v1POfMfnNBzCfaSuhtOwx1bXr+r6ATGFEbzLaDya8C+QZTQS09VF/wYJF]"
        certPassword: "![wy5qlE5XYBrKAXNkIjyTRw==]"

  sapi:
    credentials:
      clientId: "![R4JlXwbQDn1tNeuUB9t/y9YYyRdKOikOoxTyyRVOFRT1MzLu0rfp6g==]"
      clientSecret: "![rR5HLA+StUW2H7ZAsyS26M5pY2JOX4pMRVifWfunsd7qxgZagcWtLg==]"
      
error:
  sfcoresapi:
    client_id: "![l5lhPi282s0Ogb6YlYBARIg88yjTaZrZIwTUedEorH1zHMV8G3G2EA==]"
    client_secret: "![OCzpxM9WwQuXZHc5QiE8BXaKXQqO2w9LgwZzJGZ17o8a+vjnrHp/2Q==]"    
  cloudhub:
    client_id: "![+NkGJxD1W5ojRUWrl1sza3ExTyBMhwLn6AK5IvD0ngsZnXXM387ebg==]"
    client_secret: "![Yx00T6vkQE2w6ys1y58gR1wsgkIDdpDSpVNIHsDR3dmyckFVzNMPNQ==]"

aws:
  sqs:
    accessKey: "![MPCySVqny5b89iZ6rtMzfkGLeTci1LDQ]"
    secretKey: "![3HkGk6ULF+fOMRYQkN4I2kEwJwx/huxyuxdhDU1b7awhx5VkXKILIfi1q/UV77Kv]"
    arn: "![ZFjLCmMu7EzMhLQNdkT5l3hot9IAxVy569wwIup2q9yIZRla4USL+QfX86tczBy40uZ3k2qmn+URGCraYR9NKmT2fIvrXB5hertR5riz4Uc=]"
