https:
  keyPass: "![LMwU9lU49ETVhX81ziCo4w==]"

app:
  salesforce:
    cloud:
      auth:
        username: "![JD0h3saayxLmTdB/7BF9QDYatvXQh+NOQA1njUui2EJEoBXc+85IbcyXjEDF5V3P]"
        password: "![k9/vDqF8x10bDUN2qbINeg==]"
        consumerKey: "![y51djiH6fl6bvgWEhY1HX5SrqYCGYh8jGhQq3Q32cMaMFd32d6Jbyb1Itjm+I6HYmmK2WaEkrmf/O4KsyFMrfYcAbld9oBK4itvaaJQ0iDX7iDn4ZdD57Q==]"
        consumerSecret: "![INdcQuS4NRwz4cJr7eWHZiFHwiPyTyx/D9Qimz5v1POfMfnNBzCfaSuhtOwx1bXr+r6ATGFEbzLaDya8C+QZTQS09VF/wYJF]"
        certPassword: "![wy5qlE5XYBrKAXNkIjyTRw==]"

  sapi:
    credentials:
      clientId: "![R4JlXwbQDn1tNeuUB9t/y9YYyRdKOikOoxTyyRVOFRT1MzLu0rfp6g==]"
      clientSecret: "![rR5HLA+StUW2H7ZAsyS26M5pY2JOX4pMRVifWfunsd7qxgZagcWtLg==]"