#Common App Properties
api:
  id: "58798"

app:
  salesforce:
    cloud:
      auth:
        certPath:      "certs/vems-mule-sfcore-sapi.jks"
        certAlias:     "app"
        tokenEndpoint: "https://maximusves--coredev.sandbox.my.salesforce.com/services/oauth2/token"
        audienceEndpoint: "https://test.salesforce.com"
      reconnection:
        frequency:  "2000"
        attempts:   "2"
      event:
        listener:
          channel:
            name:  "/event/ClarificationRequestEvent__e"
        providerAcctUpdate:
          lstChannel:
            name: "event/Provider_Account_Update__e"
        servAppointment:
          lstChannel:
            name: "event/Provider_Last_Appointment__e"
        appointmentScheduled:
          channel:
            name: "/event/ServiceAppointment__e"
        contentionCancelation:
          channel:
            name: "/event/Contention_Cancellation_Request_Event__e"
        appointmentCanceled:
          channel:
            name: "/event/Appointment_Cancel_Request_Event__e"
        appointmentCompleted:
          channel:
            name: "/event/AppointmentCompletedEvent__e"
        providerFreezeSync:
          channel:
            name: "/event/Freeze_Created_Updated__e"
  s3:
    api:
      host: "vems-mule-aws-sapi-dev.usg-w1.gov.cloudhub.io"
      port: "80"
      url:  "/api"
      methods:
        getObject:    "/s3/objects"
        postObject:   "/s3/objects"
    credentials:
      client_id:     "e14a7d608d8c4565a7430d6dec95f83c"
      client_secret: "2D68922b82614A5EA280078eD5bD61fB"
  sfpnm:
    api:
      host: "vems-mule-sfpnm-sapi-prod.usg-w1.gov.cloudhub.io"
      port: "443"
      url:  "/api/v1"

      