#Common App Properties
api:
  id: "61007"


practiceMatch:
  host: "api-dev.practicematch.com"
  
pnmSapi:
  host: "vems-mule-sfpnm-sapi-dev.usg-w1.gov.cloudhub.io"
  
error:
  sfcoresapi:
    host: "vems-mule-sfcore-sapi-dev.usg-w1.gov.cloudhub.io"    
  cloudhub:
    environment: "075a1f44-74c5-485f-a9d3-a73d21437302"