#Common App Properties
api:
  id: "61143"

practiceMatch:
  host: "api-dev.practicematch.com"
  
pnmSapi:
  host: "vems-mule-sfpnm-sapi-qa.usg-w1.gov.cloudhub.io"
  
error:
  sfcoresapi:
    host: "vems-mule-sfcore-sapi-qa.usg-w1.gov.cloudhub.io"    
  cloudhub:
    environment: "b2adb5f0-4215-43c0-b6c3-3fa1f5480b0b"