#QA Secure App Properties
        
https:
  keyPass: "![LMwU9lU49ETVhX81ziCo4w==]"

app:
  salesforce:
    cloud:
      auth:
        username: "![EikoThIsIcs2HD7u7ePh2qxtHxU7dm+iCOQzN23VcTso506ib57EAQ==]"
        password: "![mZHZbNV+5kcSXiO2OGl0Cw==]"
        consumerKey: "![y51djiH6fl6rhF+fGCXJ7PNZ14+8SsSVwRI2BDg8nrbD1Edmztsv+CiIDTNz5oJSq+1aw3/UMwa1kc5e7zFIBhxnB1zwtrKVs1l/kzSsJbLcYMkOAzlpLA==]"
        consumerSecret: "![2QYvjKcrYeNmr1DOeK41OTPgQaEdF/YnAv4kzoF+IIXCQ2h/2nfsXOsYQc7eHrDCxC81TCaj0JZbFa8UofSoyCMbc4tfKKIA]"
        certPassword: "![wy5qlE5XYBrKAXNkIjyTRw==]"

  sapi:
    credentials:
      clientId: "![28tUamqMOYf/mthfYq2oXqvHxw6p0nbPRy1Fb5TGBRwyS1rqc1AbYw==]"
      clientSecret: "![BQfNIqoFm/C33qFhynt9rKC4iaTCheR6oGZ1I6Fk1Bgo8YRe+xIi8w==]"
      #clientId: "![R4JlXwbQDn1tNeuUB9t/y9YYyRdKOikOoxTyyRVOFRT1MzLu0rfp6g==]"
      #clientSecret: "![rR5HLA+StUW2H7ZAsyS26M5pY2JOX4pMRVifWfunsd7qxgZagcWtLg==]"
      
      
error:
  sfcoresapi:
    client_id: "![l5lhPi282s0Ogb6YlYBARIg88yjTaZrZIwTUedEorH1zHMV8G3G2EA==]"
    client_secret: "![OCzpxM9WwQuXZHc5QiE8BXaKXQqO2w9LgwZzJGZ17o8a+vjnrHp/2Q==]"
  cloudhub:
    client_id: "![+NkGJxD1W5ojRUWrl1sza3ExTyBMhwLn6AK5IvD0ngsZnXXM387ebg==]"
    client_secret: "![Yx00T6vkQE2w6ys1y58gR1wsgkIDdpDSpVNIHsDR3dmyckFVzNMPNQ==]"