#Common App Properties
api:
  id: "62506"

env.port: "${https.private.port}"
  
app:
  api:
    outbound_papi:
      url:  "https://vems-mule-documents-papi-uat.usg-w1.gov.cloudhub.io/api/s3/objects?key=#1"
  salesforce:
    cloud:
      auth:
        certPath:      "certs/vems-mule-sfcore-sapi.jks"
        certAlias:     "app"
        tokenEndpoint: "https://maximusves--coreuat.sandbox.my.salesforce.com/services/oauth2/token"
        audienceEndpoint: "https://test.salesforce.com"
      reconnection:
        frequency:  "2000"
        attempts: "2"
      api:
        host: "maximusves--coreuat.sandbox.my.salesforce.com"
        respTimeout: '60000'
  
  sfpnm:
    api:
      host: "mule-worker-internal-vems-mule-sfpnm-sapi-uat.usg-w1.gov.cloudhub.io"
      port: "8092"
      url:  "/api/v1"
      timeout: "20000"

error:
  sfcoresapi:
    host: "mule-worker-internal-vems-mule-sfcore-sapi-uat.usg-w1.gov.cloudhub.io"    
  cloudhub:
    environment: "a6b64ee8-b361-482e-ad15-369c276ee7de"