#Common App Properties
http:
  host: "0.0.0.0"
  port: "8081"
https:
  host: "0.0.0.0"
  port: "8082"

api:
  groupId:      "${api.groupId}"
  artifactId:   "${api.artifactId}"
  version:      "${api.version}"
  spec:         ""
  majorVersion: "v1"
  
json:
  logger:
    application:
      name:     "${api.artifactId}"
      version:  "${api.version}"

error:
  domain: "${api.artifactId}"
                  
target:
  account:
    objectName: "Account"
    externalId: "Account_Id__c"
    
until:
  MaxRetries: "3"
  MsBwRetries: "1000"
  
paralellForEach:
  maxConcurrency: "10"
  
http-request:
  timeout: "30000"
  
DocumentTypes:
  DBQ:
    PDF: "/DBQ/PDF/"
    XML: "/DBQ/XML/"
  CENL:
    Order Form: "/CENL/OrderForm/"
    Appointment: "/CENL/Appointment/"
  VA:
    Outbound: "/VA/Outbound/"
    Inbound:  "/VA/Inbound/"
  Misc: "/Misc/"
  Miscellaneous: "/Miscellaneous/"
  Provider:
    Dx: "/Provider/Dx/"
  Vet: "/Vet/"
  GeneralType: "/General/"
  
