#Common App Properties
api:
  id: "61006"
  
app:
  s3:
    api:
      host: "vems-mule-aws-sapi-dev.usg-w1.gov.cloudhub.io"
      port: "80"
      url:  "/api"
      methods:
        getObject:    "/s3/objects"
        postObject:   "/s3/objects"
  sfcore:
    api:
      host: "vems-mule-sfcore-sapi-dev.usg-w1.gov.cloudhub.io"
      port: "443"
      url:  "/api"
      methods:
        s3_document:                          "/s3-document"
        s3_document_update:                   "/s3-document"
        content-version-s3:                   "/content-version-s3"
        exam_scheduling_request_created:      "/exam-scheduling-request-created"
        exam_scheduling_request_cancellation: "/exam-scheduling-request-cancellation"
        rework_exam_scheduling_request:       "/rework-exam-scheduling-request-created"
    credentials:
      client_id:     "e14a7d608d8c4565a7430d6dec95f83c"
      client_secret: "2D68922b82614A5EA280078eD5bD61fB"    
  
  sfpnm:
    api:
      host: "vems-mule-sfpnm-sapi-dev.usg-w1.gov.cloudhub.io"
      port: "443"
      url:  "/api/v1"
  
  api:
    document_papi:
      url: "https://vems-mule-documents-papi-dev.usg-w1.gov.cloudhub.io/api/s3/objects?key=#1"
    document_pnm_papi:
      url: "https://vems-mule-documents-papi-dev.usg-w1.gov.cloudhub.io/api/s3/objects?source=pnm&key=#1"
      
  scheduler:
    sfpnm_to_s3: "0 59 23 ? * * *"
    sfcore_to_s3: "0 59 23 ? * * *"
      
error:
  cloudhub:
    environment: "075a1f44-74c5-485f-a9d3-a73d21437302"