#%RAML 1.0 NamedExample
[
  {
    "paymentType": "Invoive",
    "currency": "USD",
    "invoiceNumber": "example",
    "expenseItemNumber": "example",
    "expenseReportNumber": "example",
    "amount": 1000,
    "expenseReportAmountApproved": 1000,
    "payeeName": "example",
    "VESCaseID": "example",
    "expenseAppointmentNumber": "example",
    "invoiceAppointmentNumber": "example",
    "description": "example",
    "status": "Approved",
    "financialAccount": "example",
    "region": "example",
    "name": "guid",
    "purchaseOrderId": "example"
  }
]