#%RAML 1.0 NamedExample
[
    {
        "notificationId": "a3LBZ0000002glN2AQ",
        "status": "Error",
        "errorMsg": "Record ID: id value of incorrect type: a3LBZ0000002glN2AQ1"
    },
    {
        "notificationId": "a3LBZ0000002h482AA",
        "status": "Success"
    }
]