#%RAML 1.0 NamedExample
[
  {
  "caseId": "C92837432532",
  "esrId": "c56ce1e8-5553-478c-83a8-aea31a1de318",
  "caseStatus": "status1",
  "casePostDate": "2023-05-17T11:20:50.551Z",
  "caseSpecialty": "audio",
  "dbqList": ["dbq1", "dbq2"],
  "transactionId": "transaction id",
  "transactionTs": "this transaction iso date and time as string"
  }
]