#%RAML 1.0
title: DATSI - AWS S3 Connector System API
description: DATSI - AWS S3 Connector System API
version: v1
protocols:
  - HTTP

traits:
  client-id-required: !include ./exchange_modules/a49d2bd5-98e7-47cb-be7d-a153583e60a6/common-raml-fragments/1.0.0/traits/common/client-id-trait.raml
  500-trait: !include/exchange_modules/a49d2bd5-98e7-47cb-be7d-a153583e60a6/common-raml-fragments/1.0.0/traits/json/500-trait.raml

types:
  S3Object:  !include ./dataTypes/S3Object-dataType.raml

/s3/bucket:
  is:
    - client-id-required
    - 500-trait
  /{bucket}:
    get:
      responses: 
        200:
          description: Success result
          body:
            application/json:
              type: S3Object[]

/s3/objects:
  is:
    - client-id-required
    - 500-trait
  get:
    queryParameters:
      key:
        example:
          value: unique-document-name.pdf
        description: This is the S3 Object key which is unique inside S3 Bucket
        type: string
        required: true
    responses:
      200:
        headers:
          Content-Disposition?:
        body:
          application/octet-stream:
            description: Binary response object
      404:
       body:
        application/json:
          properties:
            message: string
  post:
    body:
      multipart/form-data:
        properties:
          name: string
          file:
            type: file
    responses:
      201:
        body:
          application/json:
            properties:
              message: string
              url: string
  /pnm:
    is:
    - client-id-required
    get:
      queryParameters:
        key:
          example:
            value: unique-document-name.pdf
          description: This is the S3 Object key which is unique inside S3 Bucket
          type: string
          required: true
      responses:
        200:
          headers:
            Content-Disposition?:
          body:
            application/octet-stream:
              description: Binary response object
        404:
          body:
            application/json:
              properties:
                message: string
    post:
      body:
        multipart/form-data:
          properties:
            name: string
            file:
              type: file
      responses:
        201:
          body:
            application/json:
              properties:
                message: string
                url: string
        500:
          body:
            application/json:
              properties:
                message: string  
/postgresDB:
  post:
    body:
      application/json:
        type: !include /dataTypes/postgressDB.raml
    responses:
      201:
        description: Successfully created
        body:
          application/json:
            example: !include ./example/responseSuccess.raml
      500:
        description: Internal Server Error
        body:
          application/json: 
            example: !include example/responseError.raml








