#%RAML 1.0 NamedExample
{
  "Response":[
                {
                  "ResponseID": "401772252",
                  "FirstName": "Larry",
                  "LastName": "Florman",
                  "PhoneNumbers":
                      [
                        {
                          "PhoneNumber":"502-417-5332",
                          "PhoneType":"Home"
                        }
                      ],
                  "EmailAddress": "larryflo@prodigy.net",
                  "City": "Falls Church",
                  "State": "VA",
                  "Specialty": "Surgery",
                  "AlternateOpportunityID": "875241AR",
                  "CVFileName": "",
                  "CVContents": "",
                  "ProfessionsList": "Physician (MD,DO,Resident)",
                  "ApplicationDate": "2023-07-09T19:19:39.890"
                }
            ]
}