#%RAML 1.0 NamedExample
{
  "Responses":
              [
                  {
                  "ResponseID": "401783249",
                  "AlternateOpportunityID": "#633 Neurology CA DWC Project"
                  },
                  {
                  "ResponseID": "401754846",
                  "AlternateOpportunityID": "849211BG"
                  }
          ]
}