#Common App Properties
http:
  host: "0.0.0.0"
  port: "8081"
https:
  host: "0.0.0.0"
  port: "8082"

api:
  appGroupId:      "${api.groupId}"
  appArtifactId:   "${api.artifactId}"
  appVersion:      "${api.version}"
  spec:         ""
  appMajorVersion: "v1"
  
json:
  logger:
    application:
      name:     "${api.artifactId}"
      version:  "${api.version}"
      
app:
  oracle:
    api:
      externalReportPath: "/xmlpserver/services/ExternalReportWSSService"
      url:  "/fscmRestApi/resources/11.13.18.05"
      fscmServicePath: "/fscmService/ErpIntegrationService"
      externalPayee:
        expandValue: "externalPartyPaymentMethods"
        
    
http-request:
  timeout: "20000"