#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    s3DocumentId:
      type: string
      required: false
    documentURL:
      type: string
      required: false
    notificationId:
      type: string
      required: true