#%RAML 1.0 DataType
type: object
properties:
  id:
    type: string
    required: true
  title:
    type: string
    required: true
  owner:
    type: string
    required: false
  size:
    type: number
    required: false
  description:
    type: string
    required: false
  type:
    type: string
    required: false
  extension:
    type: string
    required: false
  versionData:
    type: string
    required: false