#%RAML 1.0 DataType
properties:
  Id:
    type: string
    required: true
  Service_Appointment__c:
    type: string
    required: false
  Carrier__c:
    type: string
    required: false
  Tracking_Number__c:
    type: string
    required: false
  Emailed__c:
    type: boolean
    required: false
  Rejected__c:
    type: boolean
    required: false