#%RAML 1.0 DataType
type: object
properties:
  CE_Eligible:
    type: boolean
    required: false
  aceEligible:
    type: string
    required: false
  Address1:
    type: string
    required: false
  Address2:
    type: string
    required: false
  Address3:
    type: string
    required: false
  Adjudicated:
    type: string
    required: false
  assigningAuthority:
    type: string
    required: false
  bilateralIndicator:
    type: string
    required: false
  CancellationReason:
    type: string
    required: false
  City:
    type: string
    required: false
  clarification:
    type: string
    required: false
  Classification_code:
    type: string
    required: false
  classificationName:
    type: string
    required: false
  code:
    type: string
    required: false
  Contention_Special_Issue:
    type: string
    required: false
  contentionExternalId:
    type: string
    required: false
  contentionName:
    type: string
    required: false
  ContentionSpecialIssue:
    type: string
    required: false
  contentionType:
    type: string
    required: false
  contractorName:
    type: string
    required: false
  Country:
    type: string
    required: false
  description:
    type: string
    required: false
  Details:
    type: string
    required: false
  diagnosticCode:
    type: string
    required: false
  DirectServiceNarrativeEntry:
    type: string
    required: false
  DisabilityBilateralIndicator:
    type: string
    required: false
  DisabilityDiagnosticCode:
    type: string
    required: false
  DisabilityName:
    type: string
    required: false
  DisabilityPercentage:
    type: string
    required: false
  documentReferenceId:
    type: string
    required: false
  dodReferred:
    type: string
    required: false
  emsPointOfContact:
    type: string
    required: false
  eventDtg:
    type: string
    required: false
  EventSource:
    type: string
    required: false
  eventUuid:
    type: string
    required: false
  examAppointmentUuid:
    type: string
    required: false
  ExamContractorName:
    type: string
    required: false
  examDetails:
    type: string
    required: false
  examEventdtg:
    type: string
    required: false
  examModalVersion:
    type: string
    required: false
  examName:
    type: string
    required: false
  ExamParticpatingSystem:
    type: string
    required: false
  ExamPrioritizationSpecialIssues:
    type: string
    required: false
  examRelatedContentionUuid:
    type: string
    required: false
  examRelatedEventUuid:
    type: string
    required: false
  examRelatedPreviousEventUuid:
    type: string
    required: false
  ExamRelatedUuid:
    type: string
    required: false
  examScedulingRequestUuid:
    type: string
    required: false
  examSchedulingRequestUuid:
    type: string
    required: false
  ExamStatusUuid:
    type: string
    required: false
  examType:
    type: string
    required: false
  faulty_AppointmentUuid:
    type: string
    required: false
  faulty_contractorname:
    type: string
    required: false
  faulty_details:
    type: string
    required: false
  faulty_event:
    type: string
    required: false
  faulty_examappintmentuuid:
    type: string
    required: false
  faulty_examsceduuid:
    type: string
    required: false
  faulty_modalversion:
    type: string
    required: false
  faulty_particpatingsystem:
    type: string
    required: false
  faulty_previouseventuuid:
    type: string
    required: false
  Gender_Preference_Indicator:
    type: string
    required: false
  id:
    type: string
    required: false
  insufficient:
    type: string
    required: false
  medicalOpinionNeeded:
    type: string
    required: false
  MilitaryPO:
    type: string
    required: false
  MilitaryPostalCode:
    type: string
    required: false
  modelVersion:
    type: string
    required: false
  Name:
    type: string
    required: false
  name__c:
    type: string
    required: false
  nameOfExaminer:
    type: string
    required: false
  nameOfInServiceInjuryOrEvent:
    type: string
    required: false
  narrativeEntry:
    type: string
    required: false
  participatingSystemName:
    type: string
    required: false
  percentage:
    type: number
    required: false
  phone:
    type: string
    required: false
  Preferred_Examiner_Gender:
    type: string
    required: false
  previousEventUuid:
    type: string
    required: false
  previouslyWorkedContentionUuid:
    type: string
    required: false
  ReasonForCancellation:
    type: string
    required: false
  RelatedDisabilityDiagnosticCode:
    type: string
    required: false
  RelatedDisabilityName:
    type: string
    required: false
  RelatedDisabilityPercentage:
    type: string
    required: false
  Remand_Specialist_Type:
    type: string
    required: false
  RemandSpecialistIndicator:
    type: string
    required: false
  ReworkReason:
    type: string
    required: false
  ReworkReasonFreetext:
    type: string
    required: false
  scheduledDateTime:
    type: string
    required: false
  SecondaryServiceNarrativeEntry:
    type: string
    required: false
  StandardLanguageEntry:
    type: string
    required: false
  State:
    type: string
    required: false
  Status:
    type: string
    required: false
  StringValue:
    type: string
    required: false
  subs_contractorName:
    type: string
    required: false
  subs_Details:
    type: string
    required: false
  subs_eventDtg:
    type: string
    required: false
  subs_EventUuid:
    type: string
    required: false
  subs_examAppointmentUuid:
    type: string
    required: false
  subs_ExamSchedulingRequestUuid:
    type: string
    required: false
  subs_ModelVersion:
    type: string
    required: false
  subs_participatingSystemName:
    type: string
    required: false
  subs_PreviousEventUui:
    type: string
    required: false
  systemReference:
    type: string
    required: false
  Title:
    type: string
    required: false
  UuidValue:
    type: string
    required: false
  VA_ESR:
    type: string
    required: true
  ZipOrPostalCode:
    type: string
    required: false