#%RAML 1.0 DataType
type: object
properties:
  Id:
    type: string
    required: false
  Name:
    type: string
    required: false
  name__c:
    type: string
    required: false
  NarrativeEntry:
    type: string
    required: false
  VA_Contention:
    type: string
    required: false
  VA_Contention_Name:
    type: string
    required: false
  VA_ESR:
    type: string
    required: true