#%RAML 1.0 DataType
type: object
properties:
  Address1:
    type: string
    required: false
  Address2:
    type: string
    required: false
  Address3:
    type: string
    required: false
  AlternateDestinationJustification:
    type: string
    required: false
  alternatePhone:
    type: string
    required: false
  AME:
    type: boolean
    required: false
  Appeal:
    type: boolean
    required: false
  assigningAuthority:
    type: string
    required: false
  benefitProgramType:
    type: string
    required: false
  Birthdate:
    type: date-only
    required: false
  Blue_Water:
    type: boolean
    required: false
  branchOfService:
    type: string
    required: false
  City:
    type: string
    required: false
  Claim_Information_Type:
    type: string
    required: false
  claimDate:
    type: string
    required: false
  claimLabel:
    type: string
    required: false
  claimPayeeCode:
    type: string
    required: false
  clarification:
    type: boolean
    required: false
  ClarificationReason:
    type: string
    required: false
  CLCW:
    type: boolean
    required: false
  code:
    type: string
    required: false
  Contention_Cancellation_Reason:
    type: string
    required: false
  ContentionClarificationFreeText:
    type: string
    required: false
  contentionUuid:
    type: string
    required: false
  Contract:
    type: string
    required: false
  contractorName:
    type: string
    required: false
  Country:
    type: string
    required: false
  dateOfBirth:
    type: string
    required: false
  dateOfDeath:
    type: string
    required: false
  Deceased_Veteran:
    type: boolean
    required: false
  Dependent_PoaVso_Name:
    type: string
    required: false
  dependentAddress1:
    type: string
    required: false
  dependentAddress2:
    type: string
    required: false
  dependentAddress3:
    type: string
    required: false
  dependentalternatePhone:
    type: string
    required: false
  dependentCity__c:
    type: string
    required: false
  dependentCode__c:
    type: string
    required: false
  dependentCountry:
    type: string
    required: false
  dependentdescription:
    type: string
    required: false
  dependentemailAddress:
    type: string
    required: false
  dependentfirstName:
    type: string
    required: false
  dependentfullName:
    type: string
    required: false
  dependentgender:
    type: string
    required: false
  dependentgeoAddress1:
    type: string
    required: false
  dependentgeoAddress2:
    type: string
    required: false
  dependentgeoAddress3:
    type: string
    required: false
  dependentgeoCity:
    type: string
    required: false
  dependentgeoCountry:
    type: string
    required: false
  dependentgeodescription:
    type: string
    required: false
  dependentgeoMilitaryPO:
    type: string
    required: false
  dependentgeoMilitaryPostalCode:
    type: string
    required: false
  dependentgeoState:
    type: string
    required: false
  dependentgeoZipOrPostalCode:
    type: string
    required: false
  dependentlastName:
    type: string
    required: false
  dependentmiddleName:
    type: string
    required: false
  dependentMilitaryPO:
    type: string
    required: false
  dependentMilitaryPostalCode:
    type: string
    required: false
  dependentName:
    type: string
    required: false
  dependentPoaVsoAddress1:
    type: string
    required: false
  dependentPoaVsoAddress2:
    type: string
    required: false
  dependentPoaVsoAddress3:
    type: string
    required: false
  dependentPoaVsoCity:
    type: string
    required: false
  dependentPoaVsoCode:
    type: string
    required: false
  dependentPoaVsoCountry:
    type: string
    required: false
  dependentPoaVsodescription:
    type: string
    required: false
  dependentPoaVsoMilitaryPO:
    type: string
    required: false
  dependentPoaVsoMilitaryPostalCode:
    type: string
    required: false
  dependentPoaVsoName:
    type: string
    required: false
  dependentPoaVsoState:
    type: string
    required: false
  dependentPoaVsoZipOrPostalCode:
    type: string
    required: false
  dependentprimaryPhone:
    type: string
    required: false
  dependentState:
    type: string
    required: false
  dependentZipOrPostalCode:
    type: string
    required: false
  Deported:
    type: boolean
    required: false
  description:
    type: string
    required: false
  Details:
    type: string
    required: false
  diagnosticCode:
    type: string
    required: false
  Disability_name:
    type: string
    required: false
  EDIPI:
    type: string
    required: false
  emailAddress:
    type: string
    required: false
  endProductCode:
    type: string
    required: false
  entryOnDuty:
    type: string
    required: false
  Era:
    type: string
    required: false
  Event_Package_Status:
    type: string
    required: false
  Event_Package_Type:
    type: string
    required: false
  eventDtg:
    type: string
    required: false
  eventName:
    type: string
    required: false
  EventSource:
    type: string
    required: false
  eventUuid:
    type: string
    required: false
  Exam_Appointment_Uuid:
    type: string
    required: false
  Exam_Related_Contention_adjudicated:
    type: string
    required: false
  Exam_Related_Contention_dodReferred:
    type: string
    required: false
  Exam_Related_Contention_Uuid:
    type: string
    required: false
  ExamCancellationReason:
    type: string
    required: false
  ExamCancellationReasonFreeText:
    type: string
    required: false
  examSchedulingRequestUuid:
    type: string
    required: true
  # FDC__c
  fileNumber:
    type: string
    required: false
  # Financial_Hardship__c
  firstName:
    type: string
    required: false
  fullName:
    type: string
    required: false
  gender:
    type: string
    required: false
  geoAddress1:
    type: string
    required: false
  geoAddress2:
    type: string
    required: false
  geoAddress3:
    type: string
    required: false
  geoCity:
    type: string
    required: false
  geoCountry:
    type: string
    required: false
  geodescription:
    type: string
    required: false
  geoMilitaryPO:
    type: string
    required: false
  geoMilitaryPostalCode:
    type: string
    required: false
  geoState:
    type: string
    required: false
  geoZipOrPostalCode:
    type: string
    required: false
  Home_Visit:
    type: boolean
    required: false
  Homebound:
    type: boolean
    required: false
  Homeless:
    type: boolean
    required: false
  # Id
  IDES:
    type: boolean
    required: false
  # InboundRequest_External_Id__c
  Incarcerated:
    type: boolean
    required: false
  insufficient:
    type: boolean
    required: false
  Internal_Message_Id:
    type: string
    required: false
  # IsDeleted
  # LastActivityDate
  # LastModifiedById
  # LastModifiedDate
  lastName:
    type: string
    required: false
  # LastReferencedDate
  # LastViewedDate
  Medal_of_Honor:
    type: boolean
    required: false
  middleName:
    type: string
    required: false
  MilitaryPO:
    type: string
    required: false
  MilitaryPostalCode:
    type: string
    required: false
  modelVersion:
    type: string
    required: false
  mscaddress1:
    type: string
    required: false
  mscaddress2:
    type: string
    required: false
  mscaddress3:
    type: string
    required: false
  msccity:
    type: string
    required: false
  msccountry:
    type: string
    required: false
  Mscdescription:
    type: string
    required: false
  mscemailAddress:
    type: string
    required: false
  mscfax:
    type: string
    required: false
  mscmilitarypo:
    type: string
    required: false
  mscmilitarypostalcode:
    type: string
    required: false
  mscname:
    type: string
    required: false
  mscprimaryphone:
    type: string
    required: false
  mscsecondaryphone:
    type: string
    required: false
  mscstate:
    type: string
    required: false
  mscZipOrPostalCode:
    type: string
    required: false
  # MST__c
  # Name
  name__c:
    type: string
    required: false
  NarrativeEntry:
    type: string
    required: false
  # Nehmer__c
  # NP_TERA__c
  original_Exam_Request_Uuid:
    type: string
    required: false
  originalExamSchedulingRequestUuid:
    type: string
    required: false
  # OwnerId
  # Parent_Inbound_Request__c
  participatingSystemName:
    type: string
    required: false
  PeacetimeEra:
    type: string
    required: false
  pebloAddress1:
    type: string
    required: false
  pebloAddress2:
    type: string
    required: false
  pebloAddress3:
    type: string
    required: false
  pebloCity:
    type: string
    required: false
  pebloCountry:
    type: string
    required: false
  Peblodescription:
    type: string
    required: false
  pebloemailAddress:
    type: string
    required: false
  peblofax:
    type: string
    required: false
  pebloMilitaryPO:
    type: string
    required: false
  pebloMilitaryPostalCode:
    type: string
    required: false
  pebloname:
    type: string
    required: false
  pebloprimaryphone:
    type: string
    required: false
  peblosecondaryphone:
    type: string
    required: false
  pebloState:
    type: string
    required: false
  pebloZipOrPostalCode:
    type: string
    required: false
  percentage:
    type: string
    required: false
  phone:
    type: string
    required: false
  PoaVsoAddress1:
    type: string
    required: false
  PoaVsoAddress2:
    type: string
    required: false
  PoaVsoAddress3:
    type: string
    required: false
  PoaVsoCity:
    type: string
    required: false
  PoaVsoCode:
    type: string
    required: false
  PoaVsoCountry:
    type: string
    required: false
  PoaVsodescription:
    type: string
    required: false
  PoaVsoMilitaryPO:
    type: string
    required: false
  PoaVsoMilitaryPostalCode:
    type: string
    required: false
  PoaVsoName:
    type: string
    required: false
  PoaVsoState:
    type: string
    required: false
  PoaVsoZipOrPostalCode:
    type: string
    required: false
  POW:
    type: boolean
    required: false
  predischargeIntakeSite:
    type: string
    required: false
  pregnant:
    type: string
    required: false
  # Pregnant_Checkbox__c
  previousEventUuid:
    type: string
    required: false
  previouslyWorkedContentionUuid:
    type: string
    required: false
  primaryPhone:
    type: string
    required: false
  radDate:
    type: string
    required: false
  Reason_for_Cancellation:
    type: string
    required: false
  regionalOfficeCode:
    type: string
    required: false
  # Remand__c
  # SFDC_VA_Inbound_Request_Record_ID__c
  # Specialist_Provider_Required__c
  # Spina_Bifida__c
  # SSSCE__c
  State:
    type: string
    required: false
  Status:
    type: string
    required: false
  Survivor_Dependent:
    type: boolean
    required: false
  Survivor_DOB:
    type: string
    required: false
  survivorOrDependentPayeeCode:
    type: string
    required: false
  # SystemModstamp
  systemReference:
    type: string
    required: false
  # Telehealth_Eligible__c
  # Terminally_Ill__c
  title:
    type: string
    required: false
  Value:
    type: string
    required: false
  Veteran_Special_Issue:
    type: string
    required: false
  X1_Year_Claim:
    type: boolean
    required: false
  X1151:
    type: boolean
    required: false
  ZipOrPostalCode:
    type: string
    required: false