#%RAML 1.0 DataType
type: object
properties:
  Disability_Name:
    type: string
    required: false
  Disability_Bilateral_Indicator:
    type: string
    required: false
  Disability_Diagnostic_Code:
    type: string
    required: false
  Disability_Percentage:
    type: string
    required: false
  ESR:
    type: string
    required: false
  Medical_Opinion_Request_Type:
    type: string
    required: false
  VA_Inbound_Request:
    type: string
    required: false
  VA_Contention:
    type: string
    required: false
  Narrative_Entry:
    type: string
    required: false
  Related_Disability_Diagnostic_Code:
    type: string
    required: false
  Name_Of_InServiceInjuryOrEvent:
    type: string
    required: false
  Medical_Opinion_Type:
    type: string
    required: false
