#Common App Properties
api:
  id: "61030"
  
env.port: "${https.port}"
    
app:
  api:
    outbound_papi:
      url:  "https://vems-mule-documents-papi-qa.usg-w1.gov.cloudhub.io/api/s3/objects?key=#1"
  salesforce:
    cloud:
      auth:
        certPath:      "certs/vems-mule-sfcore-sapi.jks"
        certAlias:     "app"
        tokenEndpoint: "https://maximusves--qa.sandbox.my.salesforce.com/services/oauth2/token"
        audienceEndpoint: "https://test.salesforce.com"
      reconnection:
        frequency:  "2000"
        attempts: "2"
      api:
        host: "maximusves--qa.sandbox.my.salesforce.com"
        respTimeout: '60000'
        
  sfpnm:
    api:
      host: "vems-mule-sfpnm-sapi-qa.usg-w1.gov.cloudhub.io"
      port: "443"
      url:  "/api/v1"
      timeout: "15000"

error:
  sfcoresapi:
    host: "vems-mule-sfcore-sapi-qa.usg-w1.gov.cloudhub.io"    
  cloudhub:
    environment: "b2adb5f0-4215-43c0-b6c3-3fa1f5480b0b"