#Common App Properties
api:
  id: "62675"
  
 
env.port: "${https.private.port}"

app:
  datsi:
    aws:
      s3:
        region: "us-gov-east-1"
        bucket: "pdf-app-s3-js-poc"
        timeout: "10000"
  pnm:
    aws:
      s3:
        region: "us-east-1"
        bucket: "max-pnm-provider-files"
        folder: "/providerfiles/"
        timeout: "10000"
        
  postgres:
    db:
      host: "max-ves-esr-db-poc.cluster-ro-c7thtp1pqvt7.us-gov-east-1.rds.amazonaws.com"
      port: "5432"
      database: "cenl_db"
      
error:
  sfcoresapi:
    host: "mule-worker-internal-vems-mule-sfcore-sapi-uat.usg-w1.gov.cloudhub.io"
    port: "8092"
  cloudhub:
    environment: "a6b64ee8-b361-482e-ad15-369c276ee7de"