https:
  keyPass: "![LMwU9lU49ETVhX81ziCo4w==]"

app: 
  sapi:
    credentials:
      clientId: "![R4JlXwbQDn1tNeuUB9t/y9YYyRdKOikOoxTyyRVOFRT1MzLu0rfp6g==]"
      clientSecret: "![rR5HLA+StUW2H7ZAsyS26M5pY2JOX4pMRVifWfunsd7qxgZagcWtLg==]"
                
practiceMatch:
  #securitytoken: "![J7DFLDTzif1+ZUFR5qiTe9mflopjJy1lhTTysgJAMuFyqBwXybmpnA==]"
  securitytoken: "![htmLgC5PFtfC4jDp2/ttsDayLa/KTE5r2yNe6Ah/04lnjoUMoWATQQ==]"
